spring:
  rabbitmq:
    username: guest
    password: guest
    addresses: 10.0.0.7:5672
    cache:
      connection:
        #       缓存连接模式,默认一个连接,多个channel
        mode: channel
#        多个连接,多个channel
#        mode: connection